name: Neuro Chord CI

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    build-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Type check
              run: bun x tsc --noEmit

            - name: Build Frontend
              working-directory: ./apps/mobile
              run: bun run build
              env:
                  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
